### ISSUE TITLE
Mac m2机器，本地debug运行跟踪，一直卡住没反应

### ISSUE THREAD

**Issue by foundwant** [lxulxu/pdf-to-markdown#3]
<img width="862" alt="image" src="https://github.com/lxulxu/pdf-to-markdown/assets/25786509/65a85d58-e5d4-467c-9dda-178878caead4">
运行到paddleorcr.py的上述位置，就没响应了。是不是不支持m2芯片环境

本地start.py运行debug代码如下：

<img width="888" alt="image" src="https://github.com/lxulxu/pdf-to-markdown/assets/25786509/86043494-2133-41d2-be9d-e5159ba74f4f">

**Comment by lxulxu** [comment]
官网说法是支持的，如果按照官网指示没有验证安装成功，可以试试旧版本。
